### ISSUE TITLE
Blank page after activating AdditionalPages

### ISSUE THREAD

**Issue by repiuk** [Piwigo/AdditionalPages#5]
If I activate AdditionalPages the piwigo website goes blank. The admin interface is visible until I select the AdditionalPages plugin page.

**Comment by erAck** [comment]
I believe this is the same cause that rendered my site completely inaccessible after having installed this plugin, though not a blank page but an error message:

```
Warning:  [mysql erropiwigoror in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups IS NULL OR groups REGEXP CONCAT("(^|,)",group_id,"(,|$)"))
  AND level <=' at line 7
SELECT DISTINCT id, title, permalink
FROM piwigo_additionalpages
LEFT JOIN piwigo_user_group
  ON user_id = 2
WHERE (lang IS NULL OR lang = "en_GB")
  AND (users IS NULL OR users LIKE "%guest%")
  AND (groups IS NULL OR groups REGEXP CONCAT("(^|,)",group_id,"(,|$)"))
  AND level <= 0
  AND pos >= 0
ORDER BY pos ASC
; in /piwigo/gallery/include/dblayer/functions_mysqli.inc.php on line 856


Fatal error: Uncaught Error: Call to a member function fetch_assoc() on boolean in /piwigo/include/dblayer/functions_mysqli.inc.php:220
Stack trace:
#0 /piwigo/plugins/AdditionalPages/main.inc.php(124): pwg_db_fetch_assoc(false)
#1 /piwigo/include/functions_plugins.inc.php(264): ap_apply(Array)
#2 /piwigo/include/block.class.php(181): trigger_notify('blockmanager_ap...', Array)
#3 /piwigo/include/menubar.inc.php(342): BlockManager->apply('MENUBAR', 'menubar.tpl')
#4 /piwigo/include/menubar.inc.php(15): initialize_menu()
#5 /piwigo/index.php(103): include('/piwigo...')
#6 {main} thrown in /piwigo/include/dblayer/functions_mysqli.inc.php on line 220
```

Also, in the Admin interface (luckily I still had that open in another browser tab) when clicking the plugin I got
```
Warning:  [mysql error 1146] Table 'piwigodb.piwigo_additionalpages' doesn't exist
SELECT id
FROM piwigo_additionalpages
LIMIT 1
; in /piwigo/gallery/include/dblayer/functions_mysqli.inc.php on line 856


Fatal error: Uncaught Error: Call to a member function fetch_assoc() on boolean in /piwigo/gallery/include/dblayer/functions_mysqli.inc.php:917
Stack trace:
#0 /piwigo/include/functions.inc.php(1538): query2array('SELECT id\nFROM ...', NULL, 'id')
#1 /piwigo/plugins/AdditionalPages/admin.php(15): array_from_query('SELECT id\nFROM ...', 'id')
#2 /piwigo/admin/plugin.php(53): include_once('/piwigo...')
#3 /piwigo/admin.php(309): include('/piwigo...')
#4 {main} thrown in /piwigo/include/dblayer/functions_mysqli.inc.php on line 917
```
Removing the plugin made things work again.

I think the cause is using an unquoted **groups** column name, which is a reserved word in MySQL 8, and already creating the piwigo_additionalpages table with that column name fails, and all further places that use the groups column name unquoted fail alike.
